eBookDelivery/eBookDelivery/Models/ApplicationUsers.cs
using eBookDelivery.Data.Enum;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Models
{
    public class ApplicationUsers : IdentityUser
    {
        [Display(Name = "Full name ")]
        [Required(ErrorMessage = "Full name is required")]
        public string FullName { get; set; }
        public UserType UserType { get; set; }
    }
}

eBookDelivery/eBookDelivery/Models/Book.cs
using eBookDelivery.Data.Enum;
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Models
{
    public class Book
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Book name is required")]
        [Display(Name = "Book Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Author is required")]
        [Display(Name = "Author name")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [Display(Name = "Description")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Price is required")]
        [Display(Name = "Enter price")]
        public double Price { get; set; }
        public string BookPictureUrl { get; set; }

        [Required(ErrorMessage = "Book picture is required")]
        [Display(Name = "Book Picture")]
        [NotMapped]
        public IFormFile BookPicture { get; set; }

        [Display(Name = "Avilable")]
        public Avilable Avilable { get; set; }

        [Required(ErrorMessage = "BookCategory is required")]
        [Display(Name = "Select book category")]
        public BookCategory BookCategory { get; set; }

        //Relationship
        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher Publisher { get; set; }
    }
}

eBookDelivery/eBookDelivery/Models/ErrorViewModel.cs
using System;

namespace eBookDelivery.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

eBookDelivery/eBookDelivery/Models/Publisher.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Models
{
    public class Publisher
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Full name is required")]
        [Display(Name = "Full name")]
        public string FullName { get; set; }

        public string ProfilePictureURL { get; set; }

        [Required(ErrorMessage = "Profile picture is required")]
        [Display(Name = "Profile picture")]
        [NotMapped]
        public IFormFile ProfilePicture { get; set; }

        [Required(ErrorMessage = "Address is required")]
        [Display(Name = "Address")]
        public string Address { get; set; }

        [Required(ErrorMessage = "Email address is required")]
        [Display(Name = "Email address")]
        public string EmailAddress { get; set; }
        public List<Book> Books { get; set; }

    }
}

eBookDelivery/eBookDelivery/Controllers/AccountController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Controllers
{
    public class AccountController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

eBookDelivery/eBookDelivery/Controllers/BookController.cs
using eBookDelivery.Data;
using eBookDelivery.Data.Services;
using eBookDelivery.Data.ViewModel;
using eBookDelivery.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookService _service;
        public BookController(IBookService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            return View(_service.GetAllAsync());
        }

        public async Task<IActionResult> Create()
        {
            var bookDropDownData = await _service.GetDropDownValueAsync();
            ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "FullName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name,Author,Price,BookPicture,Avilable,BookCategory,Description,PublisherId")] Book book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetDropDownValueAsync();
                ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "FullName");
                return View(book);
            }
            await _service.CreateAsync(book);
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Update(int id)
        {
            var bookDetails = await _service.GetByIdAsync(id);
            var bookDropDownData = await _service.GetDropDownValueAsync();
            ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "FullName");
            return View(bookDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Book book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropDownData = await _service.GetDropDownValueAsync();
                ViewBag.Publishers = new SelectList(bookDropDownData.Publishers, "Id", "FullName");
                return View(book);
            }
            await _service.UpdateAsync(book);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Details(int id)
        {
           var bookDetails = _service.Details(id);
            if(bookDetails == null)
            {
                return View("Not Found");
            }
            return View(bookDetails);
        }
    }
}

eBookDelivery/eBookDelivery/Controllers/PublisherController.cs
using eBookDelivery.Data.Services;
using eBookDelivery.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eBookDelivery.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherService _service;
        public PublisherController(IPublisherService service)
        {
            _service = service;
        }
        public IActionResult Index()
        {
            return View(_service.GetAll());
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePicture,Address,EmailAddress")] Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            await _service.CreateAsync(publisher);
            return RedirectToAction(nameof(Index));

        }
        public IActionResult Details(int id)
        {
            var userDetails = _service.Details(id);
            if (userDetails == null)
            {
                return View("Not Found");
            }
            return View(userDetails);
        }
        public IActionResult Delete(int id)
        {
            var userDetails = _service.Details(id);
            if (userDetails == null)
            {
                return View("Not Found");
            }
            return View(userDetails);
        }
        public async Task<IActionResult> Deleted(int id)
        {
            await _service.Delete(id);
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Update(int id)
        {
            var userDetails = _service.Details(id);
            if (userDetails == null)
            {
                return View("Not Found");
            }
            return View(userDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Update(Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            await _service.Update(publisher);
            return RedirectToAction(nameof(Index));
        }
    }
}

eBookDelivery/eBookDelivery/Views/Book/Create.cshtml
@model Book
@using eBookDelivery.Data.Enum;
@{ ViewData["Title"] = "Create a new Book"; }
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Book</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form enctype="multipart/form-data" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="Name" class="control-lable"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Author" class="control-lable"></label>
                                <input asp-for="Author" class="form-control" />
                                <span asp-validation-for="Author" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-lable"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>


                            <div class="form-group">
                                <label asp-for="BookPicture" class="control-lable"></label>
                                <div class="custom-file">
                                    <input asp-for="BookPicture" class="custom-file-input" id="ProfilePicture"
                                           onchange="document.getElementById('PosterImagePreview').src = window.URL.createObjectURL(this.files[0])" />
                                    <lable class="custom-file-label" for="Logo">Choose File</lable>
                                    <span asp-validation-for="BookPicture" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-lable"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Avilable" class="control-lable"></label>
                                <select asp-for="Avilable" class="form-control" asp-items="Html.GetEnumSelectList<Avilable>()"></select>
                                <span asp-validation-for="Avilable" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-lable"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-lable"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img class="border-info rounded-circle" style="width:100%;" id="PosterImagePreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>$(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });</script>

}

eBookDelivery/eBookDelivery/Views/Book/Details.cshtml
@model Book
@{
    ViewData["Titile"] = "Show book details";
}
<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="~/images/books/@Model.BookPictureUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">
                            <b>Publisher: </b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.Publisher">
                                @Model.Publisher.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.BookCategory</p>
                        <p class="card-text"><b>Category: </b>@Model.Author</p>
                        <p class="card-text">
                            <b>Description: </b>
                            @Model.Description
                        </p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (Model.Avilable.ToString().Contains("Avilable"))
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else
                            {
                                <span class="badge bg-danger text-white">Unavilable</span>
                            }
                        </p>
                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            @if (Model.Avilable.ToString().Contains("Avilable"))
                            {
                                <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                            }
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

eBookDelivery/eBookDelivery/Views/Book/Index.cshtml
@model IEnumerable<Book>

@{
    ViewData["Title"] = "List of books";
}
<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-3 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width:251px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <a asp-action="Details" asp-route-id="@item.Id">
                            <img src="~/images/books/@item.BookPictureUrl" style="height:300px; width:250px" alt="@item.Name">
                        </a>
                    </div>
                    <div class="col-md-12">
                        <div class="card-body">
                            <p class="card-title">
                                <b>
                                    Name: @item.Name <a class="text-black float-right" asp-action="Update" asp-route-id="@item.Id"><i class="bi bi-plus-circle"></i>Edit</a>
                                </b>
                                <br />
                            </p>
                            <p class="card-text text-black">
                                <b>Author: </b>@item.Author <br />
                                <b>Publisher: </b><a class="text-black" asp-action="Details" asp-controller="Publisher" asp-route-id="@item.Id"> @item.Publisher.FullName</a>
                            </p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (item.Avilable.ToString().Contains("Avilable"))
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else
                                {
                                    <span class="badge bg-danger text-white">Unavilable</span>
                                }
                            </p>
                            <p class="card-text text-black">
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }
</div>
<div style="position:fixed; right:25px; bottom:65px;" class="text-white">
    <a asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i>
        Add New
    </a>
</div>

eBookDelivery/eBookDelivery/Views/Book/Update.cshtml
@model Book
@using eBookDelivery.Data.Enum;

@{ ViewData["Title"] = "Update Book"; }
<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new Book</h4>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form enctype="multipart/form-data" asp-action="Update">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="Name" class="control-lable"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Author" class="control-lable"></label>
                                <input asp-for="Author" class="form-control" />
                                <span asp-validation-for="Author" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-lable"></label>
                                <input asp-for="Price" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6 ">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-lable"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Avilable" class="control-lable"></label>
                                <select asp-for="Avilable" class="form-control" asp-items="Html.GetEnumSelectList<Avilable>()"></select>
                                <span asp-validation-for="Avilable" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="BookCategory" class="control-lable"></label>
                                <select asp-for="BookCategory" class="form-control" asp-items="Html.GetEnumSelectList<BookCategory>()"></select>
                                <span asp-validation-for="BookCategory" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-lable"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="BookPicture" class="control-lable"></label>
                            <div class="custom-file">
                                <input asp-for="BookPicture" class="custom-file-input" id="ProfilePicture" placeholder="asd"
                                       onchange="document.getElementById('PosterImagePreview').src = window.URL.createObjectURL(this.files[0])" />
                                <lable class="custom-file-label" for="Logo">Choose File</lable>
                                <span asp-validation-for="BookPicture" class="text-danger"></span>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 offset-4 text-center">
                        <img src="~/images/books/@Model.BookPictureUrl" style="width:100%;" id="PosterImagePreview" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show All</a>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(document).ready



        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });</script>

}

eBookDelivery/eBookDelivery/Views/Publisher/Create.cshtml
@model Publisher
@{ ViewData["Title"] = "Create a publisher"; }


<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Add a new Publisher</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form enctype="multipart/form-data" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger">
                    </div>
                    @* <vc:image-uploader field-name="@nameof(Model.ProfilePicture)"></vc:image-uploader>*@
                    <div class="form-group text-center">
                        <img style="max-width:150px;" id="ProfilePicturePreview" />
                    </div>
                    <div class="form-group">
                        <label asp-for="ProfilePicture" class="control-lable"></label>
                        <div class="custom-file">
                            <input asp-for="ProfilePicture" class="custom-file-input" id="ProfilePicture"
                                   onchange="document.getElementById('ProfilePicturePreview').src = window.URL.createObjectURL(this.files[0])" />
                            <lable class="custom-file-label" for="ProfilePicture">Choose File</lable>
                            <span asp-validation-for="ProfilePicture" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="FullName" class="control-lable"></label>
                        <input asp-for="FullName" class="form-control" />
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="EmailAddress" class="control-lable"></label>
                        <input asp-for="EmailAddress" class="form-control" />
                        <span asp-validation-for="EmailAddress" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Address" class="control-lable"></label>
                        <input asp-for="Address" class="form-control" />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="name" value="Create" class="btn btn-success float-right" />
                        <a asp-action="Index" class="btn btn-success">Show All</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>$(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });</script>
}

eBookDelivery/eBookDelivery/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eBookDelivery</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Book" asp-action="Index">eBookDelivery</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Publisher" asp-action="Index"><i class="bi bi-camera-reels"></i> Publishers</a>
                                <a class="dropdown-item" asp-controller="Member" asp-action="Users"><i class="bi bi-headset"></i> Users</a>
                                <a class="dropdown-item" asp-controller="Member" asp-action="UsersRequest"><i class="bi bi-headset"></i> Users Approval Request</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="RegisterByAdmin">Create Account</a>
                        </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Book" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a book..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i>Search</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - eBookDelivery
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>